name: llm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - pytorch-gpu
  - pytorch-cuda
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu125
    - torch
    - transformers
    # - transformers[sentencepiece]==4.55.0
    - accelerate
    - kernels
    - python-multipart
    # - sentencepiece==0.2.0
    - bitsandbytes
